package com.mi.model;

// Generated 4 Sep, 2017 7:21:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyMaster generated by hbm2java
 */
@Entity
@Table(name = "company_master", catalog = "ERP")
public class CompanyMaster implements java.io.Serializable {

	private int id;
	private CompanySizeMaster companySizeMaster;
	private CompanyTypeMaster companyTypeMaster;
	private CountryMaster countryMaster;
	private String companyName;
	private Date addDate;
	private String status;
	private Set<CompanyAdminMaster> companyAdminMasters = new HashSet<CompanyAdminMaster>(
			0);

	public CompanyMaster() {
	}

	public CompanyMaster(int id, CompanySizeMaster companySizeMaster,
			CompanyTypeMaster companyTypeMaster, CountryMaster countryMaster,
			String companyName, Date addDate, String status) {
		this.id = id;
		this.companySizeMaster = companySizeMaster;
		this.companyTypeMaster = companyTypeMaster;
		this.countryMaster = countryMaster;
		this.companyName = companyName;
		this.addDate = addDate;
		this.status = status;
	}

	public CompanyMaster(int id, CompanySizeMaster companySizeMaster,
			CompanyTypeMaster companyTypeMaster, CountryMaster countryMaster,
			String companyName, Date addDate, String status,
			Set<CompanyAdminMaster> companyAdminMasters) {
		this.id = id;
		this.companySizeMaster = companySizeMaster;
		this.companyTypeMaster = companyTypeMaster;
		this.countryMaster = countryMaster;
		this.companyName = companyName;
		this.addDate = addDate;
		this.status = status;
		this.companyAdminMasters = companyAdminMasters;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_size_id", nullable = false)
	public CompanySizeMaster getCompanySizeMaster() {
		return this.companySizeMaster;
	}

	public void setCompanySizeMaster(CompanySizeMaster companySizeMaster) {
		this.companySizeMaster = companySizeMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_type_id", nullable = false)
	public CompanyTypeMaster getCompanyTypeMaster() {
		return this.companyTypeMaster;
	}

	public void setCompanyTypeMaster(CompanyTypeMaster companyTypeMaster) {
		this.companyTypeMaster = companyTypeMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id", nullable = false)
	public CountryMaster getCountryMaster() {
		return this.countryMaster;
	}

	public void setCountryMaster(CountryMaster countryMaster) {
		this.countryMaster = countryMaster;
	}

	@Column(name = "company_name", nullable = false, length = 100)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "add_date", nullable = false, length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyMaster")
	public Set<CompanyAdminMaster> getCompanyAdminMasters() {
		return this.companyAdminMasters;
	}

	public void setCompanyAdminMasters(
			Set<CompanyAdminMaster> companyAdminMasters) {
		this.companyAdminMasters = companyAdminMasters;
	}

}
