package com.mi.model;

// Generated 4 Sep, 2017 7:21:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanySizeMaster generated by hbm2java
 */
@Entity
@Table(name = "company_size_master", catalog = "ERP")
public class CompanySizeMaster implements java.io.Serializable {

	private int id;
	private String companySize;
	private Date addDate;
	private String status;
	private Set<CompanyMaster> companyMasters = new HashSet<CompanyMaster>(0);

	public CompanySizeMaster() {
	}

	public CompanySizeMaster(int id, String companySize, Date addDate,
			String status) {
		this.id = id;
		this.companySize = companySize;
		this.addDate = addDate;
		this.status = status;
	}

	public CompanySizeMaster(int id, String companySize, Date addDate,
			String status, Set<CompanyMaster> companyMasters) {
		this.id = id;
		this.companySize = companySize;
		this.addDate = addDate;
		this.status = status;
		this.companyMasters = companyMasters;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "company_size", nullable = false, length = 50)
	public String getCompanySize() {
		return this.companySize;
	}

	public void setCompanySize(String companySize) {
		this.companySize = companySize;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "add_date", nullable = false, length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companySizeMaster")
	public Set<CompanyMaster> getCompanyMasters() {
		return this.companyMasters;
	}

	public void setCompanyMasters(Set<CompanyMaster> companyMasters) {
		this.companyMasters = companyMasters;
	}

}
