package com.mi.model;

// Generated 6 Sep, 2017 12:47:17 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CompanyAdminMaster generated by hbm2java
 */
@Entity
@Table(name = "company_admin_master", catalog = "ERP", uniqueConstraints = @UniqueConstraint(columnNames = {
		"mobile_no", "email" }))
public class CompanyAdminMaster implements java.io.Serializable {

	private String uuid;
	private CompanyMaster companyMaster;
	private String firstName;
	private String middleName;
	private String lastName;
	private String mobileNo;
	private String email;
	private String password;
	private long addDate;
	private String status;

	public CompanyAdminMaster() {
	}

	public CompanyAdminMaster(String uuid, CompanyMaster companyMaster,
			String firstName, String mobileNo, String email, String password,
			long addDate, String status) {
		this.uuid = uuid;
		this.companyMaster = companyMaster;
		this.firstName = firstName;
		this.mobileNo = mobileNo;
		this.email = email;
		this.password = password;
		this.addDate = addDate;
		this.status = status;
	}

	public CompanyAdminMaster(String uuid, CompanyMaster companyMaster,
			String firstName, String middleName, String lastName,
			String mobileNo, String email, String password, long addDate,
			String status) {
		this.uuid = uuid;
		this.companyMaster = companyMaster;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.email = email;
		this.password = password;
		this.addDate = addDate;
		this.status = status;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_uuid", nullable = false)
	public CompanyMaster getCompanyMaster() {
		return this.companyMaster;
	}

	public void setCompanyMaster(CompanyMaster companyMaster) {
		this.companyMaster = companyMaster;
	}

	@Column(name = "first_name", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name", length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "mobile_no", nullable = false, length = 15)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "add_date", nullable = false)
	public long getAddDate() {
		return this.addDate;
	}

	public void setAddDate(long addDate) {
		this.addDate = addDate;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
