package com.mi.model;

// Generated 6 Sep, 2017 12:47:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompanySizeMaster generated by hbm2java
 */
@Entity
@Table(name = "company_size_master", catalog = "ERP")
public class CompanySizeMaster implements java.io.Serializable {

	private String uuid;
	private String companySize;
	private String status;
	private Set<CompanyMaster> companyMasters = new HashSet<CompanyMaster>(0);

	public CompanySizeMaster() {
	}

	public CompanySizeMaster(String uuid, String companySize, String status) {
		this.uuid = uuid;
		this.companySize = companySize;
		this.status = status;
	}

	public CompanySizeMaster(String uuid, String companySize, String status,
			Set<CompanyMaster> companyMasters) {
		this.uuid = uuid;
		this.companySize = companySize;
		this.status = status;
		this.companyMasters = companyMasters;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "company_size", nullable = false, length = 50)
	public String getCompanySize() {
		return this.companySize;
	}

	public void setCompanySize(String companySize) {
		this.companySize = companySize;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companySizeMaster")
	public Set<CompanyMaster> getCompanyMasters() {
		return this.companyMasters;
	}

	public void setCompanyMasters(Set<CompanyMaster> companyMasters) {
		this.companyMasters = companyMasters;
	}

}
