package com.mi.model;

// Generated Sep 7, 2017 4:40:22 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DepartmentMaster generated by hbm2java
 */
@Entity
@Table(name = "department_master", catalog = "crust_erp")
public class DepartmentMaster implements java.io.Serializable {

	private String uuid;
	private BranchMaster branchMaster;
	private String departmentName;
	private String status;
	private long addDate;
	private long modifyDate;

	public DepartmentMaster() {
	}

	public DepartmentMaster(String uuid, BranchMaster branchMaster,
			String departmentName, String status, long addDate, long modifyDate) {
		this.uuid = uuid;
		this.branchMaster = branchMaster;
		this.departmentName = departmentName;
		this.status = status;
		this.addDate = addDate;
		this.modifyDate = modifyDate;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_uuid", nullable = false)
	public BranchMaster getBranchMaster() {
		return this.branchMaster;
	}

	public void setBranchMaster(BranchMaster branchMaster) {
		this.branchMaster = branchMaster;
	}

	@Column(name = "department_name", nullable = false, length = 50)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "add_date", nullable = false)
	public long getAddDate() {
		return this.addDate;
	}

	public void setAddDate(long addDate) {
		this.addDate = addDate;
	}

	@Column(name = "modify_date", nullable = true)
	public long getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(long modifyDate) {
		this.modifyDate = modifyDate;
	}

}
