package com.mi.model;

// Generated 4 Sep, 2017 7:21:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginManager generated by hbm2java
 */
@Entity
@Table(name = "login_manager", catalog = "ERP")
public class LoginManager implements java.io.Serializable {

	private int id;
	private UserTypeMaster userTypeMaster;
	private int userId;
	private Date loginTime;
	private Date logoutTime;

	public LoginManager() {
	}

	public LoginManager(int id, UserTypeMaster userTypeMaster, int userId) {
		this.id = id;
		this.userTypeMaster = userTypeMaster;
		this.userId = userId;
	}

	public LoginManager(int id, UserTypeMaster userTypeMaster, int userId,
			Date loginTime, Date logoutTime) {
		this.id = id;
		this.userTypeMaster = userTypeMaster;
		this.userId = userId;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_type_id", nullable = false)
	public UserTypeMaster getUserTypeMaster() {
		return this.userTypeMaster;
	}

	public void setUserTypeMaster(UserTypeMaster userTypeMaster) {
		this.userTypeMaster = userTypeMaster;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", length = 19)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_time", length = 19)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

}
