package com.mi.model;

// Generated 6 Sep, 2017 12:47:17 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * LoginManager generated by hbm2java
 */
@Entity
@Table(name = "login_manager", catalog = "crust_erp")
public class LoginManager implements java.io.Serializable {

	private String uuid;
	private UserTypeMaster userTypeMaster;
	private String userUuid;
	private Long loginTime;
	private Long logoutTime;

	public LoginManager() {
	}

	public LoginManager(String uuid, UserTypeMaster userTypeMaster,
			String userUuid) {
		this.uuid = uuid;
		this.userTypeMaster = userTypeMaster;
		this.userUuid = userUuid;
	}

	public LoginManager(String uuid, UserTypeMaster userTypeMaster,
			String userUuid, Long loginTime, Long logoutTime) {
		this.uuid = uuid;
		this.userTypeMaster = userTypeMaster;
		this.userUuid = userUuid;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
	}

	@Id
	@GeneratedValue(generator = "uuid2")
	@GenericGenerator(name = "uuid2", strategy = "uuid2")
	@Column(name = "uuid", unique = true, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_type_uuid", nullable = false)
	public UserTypeMaster getUserTypeMaster() {
		return this.userTypeMaster;
	}

	public void setUserTypeMaster(UserTypeMaster userTypeMaster) {
		this.userTypeMaster = userTypeMaster;
	}

	@Column(name = "user_uuid", nullable = false, length = 36)
	public String getUserUuid() {
		return this.userUuid;
	}

	public void setUserUuid(String userUuid) {
		this.userUuid = userUuid;
	}

	@Column(name = "login_time")
	public Long getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Long loginTime) {
		this.loginTime = loginTime;
	}

	@Column(name = "logout_time")
	public Long getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Long logoutTime) {
		this.logoutTime = logoutTime;
	}

}
