package com.mi.model;

// Generated 6 Sep, 2017 12:47:17 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SuperAdminMaster generated by hbm2java
 */
@Entity
@Table(name = "super_admin_master", catalog = "crust_erp", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class SuperAdminMaster implements java.io.Serializable {

	private String uuid;
	private String email;
	private String password;
	private long addDate;
	private String status;

	public SuperAdminMaster() {
	}

	public SuperAdminMaster(String uuid, String email, String password,
			long addDate, String status) {
		this.uuid = uuid;
		this.email = email;
		this.password = password;
		this.addDate = addDate;
		this.status = status;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "email", unique = true, nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "add_date", nullable = false)
	public long getAddDate() {
		return this.addDate;
	}

	public void setAddDate(long addDate) {
		this.addDate = addDate;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
