package com.mi.model;

// Generated 4 Sep, 2017 7:21:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserTypeMaster generated by hbm2java
 */
@Entity
@Table(name = "user_type_master", catalog = "ERP")
public class UserTypeMaster implements java.io.Serializable {

	private int id;
	private String userType;
	private Date addDate;
	private String status;
	private String userTypeDescription;
	private Set<LoginManager> loginManagers = new HashSet<LoginManager>(0);

	public UserTypeMaster() {
	}

	public UserTypeMaster(int id, String userType, Date addDate, String status) {
		this.id = id;
		this.userType = userType;
		this.addDate = addDate;
		this.status = status;
	}

	public UserTypeMaster(int id, String userType, Date addDate, String status,
			String userTypeDescription, Set<LoginManager> loginManagers) {
		this.id = id;
		this.userType = userType;
		this.addDate = addDate;
		this.status = status;
		this.userTypeDescription = userTypeDescription;
		this.loginManagers = loginManagers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_type", nullable = false, length = 15)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "add_date", nullable = false, length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "user_type_description", length = 140)
	public String getUserTypeDescription() {
		return this.userTypeDescription;
	}

	public void setUserTypeDescription(String userTypeDescription) {
		this.userTypeDescription = userTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTypeMaster")
	public Set<LoginManager> getLoginManagers() {
		return this.loginManagers;
	}

	public void setLoginManagers(Set<LoginManager> loginManagers) {
		this.loginManagers = loginManagers;
	}

}
