package com.mi.model;

// Generated 6 Sep, 2017 12:47:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserTypeMaster generated by hbm2java
 */
@Entity
@Table(name = "user_type_master", catalog = "crust_erp")
public class UserTypeMaster implements java.io.Serializable {

	private String uuid;
	private String userType;
	private String userTypeDescription;
	private Set<LoginManager> loginManagers = new HashSet<LoginManager>(0);

	public UserTypeMaster() {
	}

	public UserTypeMaster(String uuid, String userType) {
		this.uuid = uuid;
		this.userType = userType;
	}

	public UserTypeMaster(String uuid, String userType,
			String userTypeDescription, Set<LoginManager> loginManagers) {
		this.uuid = uuid;
		this.userType = userType;
		this.userTypeDescription = userTypeDescription;
		this.loginManagers = loginManagers;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false, length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "user_type", nullable = false, length = 15)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "user_type_description", length = 140)
	public String getUserTypeDescription() {
		return this.userTypeDescription;
	}

	public void setUserTypeDescription(String userTypeDescription) {
		this.userTypeDescription = userTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTypeMaster")
	public Set<LoginManager> getLoginManagers() {
		return this.loginManagers;
	}

	public void setLoginManagers(Set<LoginManager> loginManagers) {
		this.loginManagers = loginManagers;
	}

}
